"""Add foreign key cascade and relationships

Revision ID: 65ccad9ea82c
Revises: 75d1289d7b6e
Create Date: 2026-05-15 15:01:59.741418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ccad9ea82c'
down_revision: Union[str, Sequence[str], None] = '75d1289d7b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_supplier_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_created_by_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('suppliers', 'wechat',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('suppliers', 'country',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('suppliers', 'website',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('suppliers', 'alibaba_store',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_foreign_key(None, 'suppliers', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.alter_column('suppliers', 'alibaba_store',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('suppliers', 'website',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('suppliers', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('suppliers', 'address',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('suppliers', 'wechat',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_created_by_fkey'), 'products', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('products_supplier_id_fkey'), 'products', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
